FROM ubuntu:latest

MAINTAINER Brandon Downs

CMD tail -f /dev/null

RUN apt-get update -y && apt-get install -y python3-pip python-dev

EXPOSE 80
EXPOSE 5000

COPY ./requirements.txt /API/requirements.txt

WORKDIR /API

RUN pip3 install -r requirements.txt

COPY . /API

ENTRYPOINT [ "python3" ]
CMD [ "app.py" ]